@adminToken = 

@staffToken = 

@url = http://127.0.0.1:4000


# Get all users
GET {{url}}/api/users
Authorization: Bearer {{adminToken}}

###

# Get one user
GET {{url}}/api/users/5f1356aeeb3bb1d9068bdc70
Authorization: Bearer {{adminToken}}

###

# Add new user
POST {{url}}/api/users
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@admin.com",
    "password": "secret",
    "role": "super-admin"
}

###

# Update user data
PUT {{url}}/api/users/5f135f8fb46fa1de4df589c1
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "New User Name",
    "email": "new-email@gmail.com",
    "password": "123456"
}

### 

# Delete user data
DELETE {{url}}/api/users/5f1371008fc230e3d806c423
Content-Type: application/json
Authorization: Bearer {{adminToken}}

###


# LEADS ENDPOINTS


# Get all leads
GET {{url}}/api/leads
Authorization: Bearer {{staffToken}}

###

# Get one lead
GET {{url}}/api/leads/5f1430899287b44366100faa
Authorization: Bearer {{staffToken}}

###

# Add new lead
POST {{url}}/api/leads
Authorization: Bearer {{staffToken}}
Content-Type: application/json

{
    "name": "New Clint",
    "email": "new@gmail.com",
    "phone": "1234564"
}

###

# Update user data
PUT {{url}}/api/leads/5f1430899287b44366100faa
Authorization: Bearer {{staffToken}}
Content-Type: application/json

{
    "name": "New Lead Name",
    "email": "new-email@gmail.com",
    "phone": "123456"
}

### 

# Delete user data
DELETE {{url}}/api/leads/5f1430899287b44366100faa
Content-Type: application/json
Authorization: Bearer {{staffToken}}


###

# AUTH ENDPOINTS


# Login
POST {{url}}/api/auth/login
Content-Type: application/json

{
    "email": "staff@gmail.com",
    "password": "123456"
}

###

# Get profile
GET {{url}}/api/auth/user
Authorization: Bearer {{adminToken}}